[package]
name = "stressor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "*"
egui = "0.32.0"
sysinfo = "*"
wmi = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
once_cell = "1.18"
